#!/bin/bash

while [[ $# -gt 0 ]]; do
    WORD="$1"

    case $WORD in
        -s|--skip)
            SKIPSEARCH=YES
        ;;
        -u|--username)
            USERNAME="$2"
            shift
        ;;
        -k|--key)
            KEY="$2"
            shift
        ;;
        --default)
            DEFAULT=YES
        ;;
        *)

        ;;
    esac
    shift
done

if [[ -n $SKIPSEARCH ]]; then
    echo "[INFO]Skipping the proxy searching process."
else
    echo "[INFO]Fetching avaliable proxies..."
    python fetch.py
    echo "[INFO]Proxy list has been output to file."
fi
if [[ ( -n $USERNAME ) && ( -n $KEY ) ]]; then
    python ./xeH.py -u $USERNAME -k $KEY $(cat urls.txt)
else
    python ./xeH.py $(cat urls.txt)
fi
